sudo: required
services: 
  - docker

before_install:
  - docker build -t mach1nka/docker-production-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true mach1nka/docker-production-flow npm run test