sudo: required
services: 
  - docker

before_install:
  - docker build -t mach1nka/docker-production-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true mach1nka/docker-production-flow npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "{APP_NAME}"
  env: "{ENV_NAME}"
  bucket_name: "{S3_BUCKET_NAME}"
  bucket_path: "{S3_BUCKET_PATH}"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"